    p, role:default/platform_admin, catalog-entity, read, allow
    p, role:default/platform_admin, catalog.entity.create, create, allow
    p, role:default/platform_admin, catalog.entity.update, update, allow
    p, role:default/platform_admin, catalog.entity.delete, delete, allow
    p, role:default/platform_admin, catalog.location.create, create, allow
    p, role:default/platform_admin, catalog.location.read, read, allow
    p, role:default/platform_admin, catalog.location.update, update, allow
    p, role:default/platform_admin, catalog.location.delete, delete, allow
    p, role:default/platform_admin, scaffolder-template, read, allow
    p, role:default/platform_admin, scaffolder.template.management, read, allow
    p, role:default/platform_admin, scaffolder.action.execute, use, allow
    p, role:default/platform_admin, scaffolder.task.create, create, allow
    p, role:default/platform_admin, scaffolder.task.read, read, allow
    p, role:default/platform_admin, policy-entity, read, allow
    p, role:default/platform_admin, policy.entity.create, create, allow
    p, role:default/platform_admin, policy.entity.update, update, allow
    p, role:default/platform_admin, policy.entity.delete, delete, allow
    p, role:default/engineering_lead, catalog-entity, read, allow
    p, role:default/engineering_lead, catalog.entity.create, create, allow
    p, role:default/engineering_lead, catalog.entity.update, update, allow
    p, role:default/engineering_lead, catalog.entity.delete, delete, allow
    p, role:default/engineering_lead, catalog.location.create, create, allow
    p, role:default/engineering_lead, catalog.location.read, read, allow
    p, role:default/engineering_lead, catalog.location.update, update, allow
    p, role:default/engineering_lead, catalog.location.delete, delete, allow
    p, role:default/engineering_lead, scaffolder-template, read, allow
    p, role:default/engineering_lead, scaffolder.template.management, read, allow
    p, role:default/engineering_lead, scaffolder.action.execute, use, allow
    p, role:default/engineering_lead, scaffolder.task.create, create, allow
    p, role:default/engineering_lead, scaffolder.task.read, read, allow
    p, role:default/senior_engineer, catalog-entity, read, allow
    p, role:default/senior_engineer, catalog.entity.create, create, allow
    p, role:default/senior_engineer, catalog.entity.update, update, allow
    p, role:default/senior_engineer, catalog.entity.delete, delete, allow
    p, role:default/senior_engineer, catalog.location.create, create, allow
    p, role:default/senior_engineer, catalog.location.read, read, allow
    p, role:default/senior_engineer, scaffolder-template, read, allow
    p, role:default/senior_engineer, scaffolder.template.management, read, allow
    p, role:default/senior_engineer, scaffolder.action.execute, use, allow
    p, role:default/senior_engineer, scaffolder.task.create, create, allow
    p, role:default/senior_engineer, scaffolder.task.read, read, allow
    p, role:default/backend_engineer, catalog-entity, read, allow
    p, role:default/backend_engineer, catalog.entity.create, create, allow
    p, role:default/backend_engineer, catalog.entity.update, update, allow
    p, role:default/backend_engineer, catalog.location.create, create, allow
    p, role:default/backend_engineer, catalog.location.read, read, allow
    p, role:default/backend_engineer, scaffolder-template, read, allow
    p, role:default/backend_engineer, scaffolder.template.management, read, allow
    p, role:default/backend_engineer, scaffolder.action.execute, use, allow
    p, role:default/backend_engineer, scaffolder.task.create, create, allow
    p, role:default/backend_engineer, scaffolder.task.read, read, allow
    p, role:default/frontend_engineer, catalog-entity, read, allow
    p, role:default/frontend_engineer, catalog.entity.create, create, allow
    p, role:default/frontend_engineer, catalog.entity.update, update, allow
    p, role:default/frontend_engineer, catalog.location.create, create, allow
    p, role:default/frontend_engineer, catalog.location.read, read, allow
    p, role:default/frontend_engineer, scaffolder-template, read, allow
    p, role:default/frontend_engineer, scaffolder.template.management, read, allow
    p, role:default/frontend_engineer, scaffolder.action.execute, use, allow
    p, role:default/frontend_engineer, scaffolder.task.create, create, allow
    p, role:default/frontend_engineer, scaffolder.task.read, read, allow
    p, role:default/product_manager, catalog-entity, read, allow
    p, role:default/product_manager, catalog.location.read, read, allow
    p, role:default/QA_engineer, catalog-entity, read, allow
    p, role:default/QA_engineer, catalog.location.read, read, allow
    p, role:default/external_contractor, catalog-entity, read, allow
    p, role:default/compliance_security, catalog-entity, read, allow
    p, role:default/compliance_security, catalog.location.read, read, allow
    p, role:default/compliance_security, policy-entity, read, allow
    p, role:default/on_call_team, catalog-entity, read, allow
    p, role:default/on_call_team, catalog.entity.update, update, allow
    p, role:default/on_call_team, catalog.location.read, read, allow