podSecurityContext:
  runAsGroup: $POSTGRES_EXPORTER_UID
  runAsUser: $POSTGRES_EXPORTER_UID
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContext: {}
config:
  logLevel: 'debug'
  extraArgs:
    - --no-collector.database
    - --no-collector.database_wraparound
    - --no-collector.locks
    - --no-collector.long_running_transactions
    - --no-collector.postmaster
    - --no-collector.process_idle
    - --no-collector.replication
    - --no-collector.replication_slot
    - --no-collector.stat_activity_autovacuum
    - --no-collector.stat_bgwriter
    - --no-collector.stat_database
    - --no-collector.stat_statements
    - --no-collector.stat_wal_receiver
    - --no-collector.wal
    - --no-collector.xlog_location
    - --collector.stat_user_tables
    - --collector.statio_user_indexes
    - --collector.statio_user_tables
  datasource:
    host: '${POSTGRES_HOST}'
    user: '${POSTGRES_USER}'
    password: '${POSTGRES_PASSWORD}'
    port: "${POSTGRES_PORT}"
    database: '${POSTGRES_DATABASE_NAME}'