apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhdh-ldap
  namespace: ${RHDH_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhdh-ldap-anyuid
  namespace: ${RHDH_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: rhdh-ldap
    namespace: ${RHDH_NAMESPACE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhdh-ldap
  namespace: ${RHDH_NAMESPACE}
  labels:
    app: rhdh-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhdh-ldap
  template:
    metadata:
      labels:
        app: rhdh-ldap
    spec:
      serviceAccountName: rhdh-ldap
      containers:
        - name: ldap-server
          image: quay.io/backstage-performance/rhdh-ldap:${RBAC_POLICY}-${BACKSTAGE_USER_COUNT}u-${GROUP_COUNT}g
          imagePullPolicy: Always
          env:
            - name: LDAP_ORGANISATION
              value: "RHDH Performance Test"
            - name: LDAP_DOMAIN
              value: "test.com"
            - name: LDAP_ADMIN_PASSWORD
              value: "admin"
            - name: LDAP_CONFIG_PASSWORD
              value: "config"
            - name: LDAP_READONLY_USER
              value: "false"
            - name: LDAP_BACKEND
              value: "mdb"
            - name: LDAP_TLS
              value: "false"
            - name: LDAP_REPLICATION
              value: "false"
            - name: KEEP_EXISTING_CONFIG
              value: "true"
            - name: LDAP_LOG_LEVEL
              value: "0"
          ports:
            - containerPort: 389
              name: ldap
              protocol: TCP
            - containerPort: 636
              name: ldaps
              protocol: TCP
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rhdh-ldap
  namespace: ${RHDH_NAMESPACE}
  labels:
    app: rhdh-ldap
spec:
  ports:
    - name: ldap
      port: 389
      protocol: TCP
      targetPort: ldap
    - name: ldaps
      port: 636
      protocol: TCP
      targetPort: ldaps
  selector:
    app: rhdh-ldap
  type: ClusterIP

